//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoalManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goal()
        {
            this.Updates = new HashSet<Update>();
        }
    
        public int GID { get; set; }
        public int UID { get; set; }
        public string Title { get; set; }
        public System.DateTime TimeFrame { get; set; }
        public string Category { get; set; }
        public double Progress { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Update> Updates { get; set; }
        public virtual User User { get; set; }
    }
}
